
TOOLDIR := tools
OBJDIR := bin

BINS := $(OBJDIR)/terrain


INCDIR := $(TOOLDIR)

TOOL_OBJS := $(TOOLDIR)/artie.o $(TOOLDIR)/libppm.o \
   $(TOOLDIR)/polyartie.o $(TOOLDIR)/linear_model.o


DBG := -g
OPT := -O0
CXX := g++ $(DBG) $(OPT) -std=c++11
